language: dart

sudo: false

dart:
  - dev
  - stable

dart_task:
  - test: --platform vm
  - test: --platform dartium
    install_dartium: true
  - dartfmt
  - dartanalyzer

cache:
  directories:
    - $HOME/.pub-cache
